
        set(CMAKE_SYSTEM_NAME Linux)
        set(CMAKE_SYSROOT "/tmp/tmp.PFEARmFDqZ")
        set(CMAKE_C_COMPILER_TARGET x86_64-mtos-linux-musl)
        set(CMAKE_CXX_COMPILER_TARGET x86_64-mtos-linux-musl)
        set(CMAKE_C_FLAGS_INIT "-static")
        set(CMAKE_CXX_FLAGS_INIT "-static")
        set(CMAKE_LINKER_TYPE LLD)
        set(CMAKE_C_COMPILER clang)
        set(CMAKE_CXX_COMPILER clang++)
        set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
        set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
        set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
        set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)