image: archlinux:latest
before_script: 
  - pacman -Syyu --noconfirm
  - pacman -S base base-devel musl cmake tar util-linux arch-install-scripts --noconfirm
Build it:
  script: bash mtos-builder.sh
  artifacts:
    paths:
      - target/system.img