image: archlinux:latest
before_script: 
  - pacman -Syyu --noconfirm
  - pacman -S base-devel musl cmake tar --noconfirm
Build it:
  script: bash mtos-builder.sh
  artifacts:
    paths:
      - target/system.img