image: fedora:latest
before_script: 
  - dnf in -y @development-tools arch-install-scripts
  - dnf in -y @development-tools wget curl arch-install-scripts bash cpio musl-gcc
Build it:
  script: bash mtos-builder.sh
  artifacts:
    paths:
      - target/system.img