#!/usr/bin/env bash
# shellcheck disable=SC2034
# Name
name=MatuushOS
# Which desktop we want?
# Options:
# - gnome
# - kde
# - xfce
# - mate
# - lxqt
# - sway
desktop=sway
# You can set this option manually, or write a case expression
dm=""
case "$desktop" in
    gnome)
        dm="gdm"
        ;;
    kde)
        dm="sddm"
        ;;
    *)
        dm="lightdm"
        ;;
esac
# Which variant we want to have?
# Choose either edge or specific Alpine base version
variant=v3.22
# Snapshot of Alpine we want to use
version=$(arch)
# Mirror you want to use for downloading the base tarball
mirror=https://dl-cdn.alpinelinux.org/alpine/$variant/releases/$version/alpine-minirootfs-3.22.1-$version.tar.gz
# Build directory
bdir=~/.mtos/build
# Packages we want to include in our version of MatuushOS 
# Please don't include packges for desktop environments, these are installed automatically via the $desktop variable
pkgs=(dbus elogind librewolf $dm flatpak rustup gcompat podman fwupd bat fastfetch networkmanager networkmanager-wifi networkmanager-bluetooth wpa_supplicant)
rm_pkgs=(firefox gnome-tour)
# Additional commands to run inside the chroot
additional_cmds=("flatpak remote-add flathub https://dl.flathub.org/repo/flathub.flatpakrepo")
# Which services to enable
svcs=(dbus elogind $dm udev networkmanager wpa_supplicant)