#!/usr/bin/env bash
# shellcheck disable=SC2034
# Name
name=MatuushOS
# Variant of the Gentoo base
variant=amd64-desktop-openrc
# Which desktop we want?
# Options:
# - gnome
# - kde
desktop=gnome
# Mirror you want to use for downloading the base tarball
mirror=https://distfiles.gentoo.org/releases/amd64/autobuilds/current-stage3-$variant
# Snapshot of Gentoo we want to use
version=$(curl $mirror/latest-stage3-$variant.txt | 
awk '{print $1}' | head -n 6 | tail --lines 1)
# Build directory
bdir=~/.mtos/build
# Packages we want to include in our version of MatuushOS (please don't include packges for desktop environments)
pkgs=(dbus sys-apps/elogind librewolf papirus-icon-theme flatpak podman fwupd bat cat fastfetch)
# Additional overlays to enable. Git overlays are not yet supported.
overlays=(librewolf)
# What use flags you want to enable. Keep in mind that if you pass in an invalid USE flag, the script will fail
flags=(dbus elogind wayland pipewire gtk thunderbolt udev alsa firmware)
# Additional commands to run inside the chroot
additional_cmds=("flatpak remote-add flathub https://dl.flathub.org/repo/flathub.flatpakrepo")
# Which services to enable
svcs=(dbus elogind display-manager udev udev-trigger udev-settle)
