name: Build and release MatuushOS system.img

on:
  schedule:
    - cron: "* * 2/15 * *"
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update
          apt install -y arch-install-scripts cpio tar bsdtar bash

      - name: Run build script
        run: |
          sudo bash mtos-builder.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: system-image
          path: target/system.img

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: system-image
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: system.img
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

