name: Build and release MatuushOS system.img

on:
  schedule:
    - cron: "0 0 * * 2"
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y arch-install-scripts cpio tar bash util-linux e2fsprogs
      - name: Run it
        run: |
          git submodule init
          git submodule update
          sudo bash mtos-builder.sh
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: system-image
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: system.img
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

